### ISSUE TITLE
buildBank.js

### ISSUE THREAD

**Issue by HuangJi** [BlockACH/ACH#3]
Send some rpcs to build `bank` document and `mutualAddress` document in mongoDB.

You may use rpcs:
- getnewaddress
- mintcolorcoin
- sendlicensetoaddress

**Comment by boolafish** [comment]
[記錄]
用 GcoinPresenter 的
- getNewAddress 會幫你順便處理掉 keypoolrefill
- mint 會直接 call mint rpc
- createLicense 會幫你 call encodelicenseinfo + sendlicensetoaddress
